#include "services/themeloader.h"
#define TOML_HEADER_ONLY 1
#include "third_party/toml.hpp"
#include <QFile>
#include <QDir>
#include <QDebug>

QMap<QString, QColor> ThemeLoader::s_defaults = {
    {"base", QColor("#1e1e2e")}, {"mantle", QColor("#181825")},
    {"crust", QColor("#11111b")}, {"surface", QColor("#313244")},
    {"overlay", QColor("#45475a")}, {"text", QColor("#cdd6f4")},
    {"subtext", QColor("#bac2de")}, {"muted", QColor("#6c7086")},
    {"accent", QColor("#89b4fa")}, {"success", QColor("#a6e3a1")},
    {"warning", QColor("#f9e2af")}, {"error", QColor("#f38ba8")},
    {"purple", QColor("#cba6f7")},
    // "Heimdall Unified" obsidian + gold tokens. Defaults are the handoff
    // values so any theme that omits them still renders coherently.
    {"gold", QColor("#E3A94B")}, {"goldMid", QColor("#C98F3C")},
    {"goldDeep", QColor("#9a6e2e")}, {"goldLight", QColor("#FFE7B6")},
    {"page", QColor("#050609")}, {"bgA", QColor("#121318")},
    {"bgB", QColor("#0a0b0e")}, {"panel", QColor("#111217")},
    {"panel2", QColor("#15161c")}, {"raise", QColor("#1b1d24")},
    {"raise2", QColor("#22242c")}, {"line", QColor("#25262e")},
    {"lineSoft", QColor("#1b1c22")}, {"hair", QColor("#0e0f13")},
    // Phase C2 atmosphere tokens (sheen/shadowInk are base colours, alpha is
    // applied at the use site; scrim bakes its alpha into #aarrggbb).
    {"sheen", QColor("#FFF0D6")}, {"shadowInk", QColor("#000000")},
    {"scrim", QColor("#C7080A0D")}, {"goldInk", QColor("#1a1206")},
    {"knob", QColor("#FFF3DF")},
};

ThemeLoader::ThemeLoader(QObject *parent) : QObject(parent), m_colors(s_defaults) {}

void ThemeLoader::loadTheme(const QString &nameOrPath, const QString &themesDir)
{
    m_colors = s_defaults;
    QString filePath;
    if (QFile::exists(nameOrPath)) {
        filePath = nameOrPath;
    } else if (!themesDir.isEmpty()) {
        filePath = QDir(themesDir).filePath(nameOrPath + ".toml");
    }
    if (filePath.isEmpty() || !QFile::exists(filePath)) {
        qWarning() << "Theme not found:" << nameOrPath;
        emit themeChanged();
        return;
    }
    try {
        auto config = toml::parse_file(filePath.toStdString());
        if (auto colors = config["colors"].as_table()) {
            for (const auto &[key, val] : *colors) {
                if (auto v = val.value<std::string>()) {
                    QString colorStr = QString::fromStdString(*v);
                    QColor c(colorStr);
                    if (c.isValid())
                        m_colors[QString::fromStdString(std::string(key))] = c;
                }
            }
        }
    } catch (const toml::parse_error &err) {
        qWarning() << "Theme parse error:" << err.what();
    }
    emit themeChanged();
}

QColor ThemeLoader::color(const QString &name) const
{
    return m_colors.value(name, s_defaults.value(name, QColor("#ff00ff")));
}

void ThemeLoader::setColor(const QString &name, const QColor &c)
{
    if (name.isEmpty() || !c.isValid())
        return;
    if (m_colors.value(name) == c)
        return;
    m_colors[name] = c;
    emit themeChanged();
}

bool ThemeLoader::saveThemeFile(const QString &path) const
{
    if (path.isEmpty())
        return false;

    // Serialise every canonical token (sorted for a stable diff) as a TOML
    // [colors] table. Tokens carrying alpha (e.g. scrim) round-trip through
    // #aarrggbb; opaque tokens stay #rrggbb.
    QString out = QStringLiteral(
        "# Heimdall custom theme — generated by the Colours settings section.\n"
        "# Edit in-app (Settings -> Look & Feel -> Colours) or by hand.\n"
        "[colors]\n");
    const auto keys = s_defaults.keys();
    for (const QString &key : keys) {
        const QColor c = m_colors.value(key, s_defaults.value(key));
        const QString hex = c.alpha() < 255 ? c.name(QColor::HexArgb)
                                            : c.name(QColor::HexRgb);
        out += key + QStringLiteral(" = \"") + hex + QStringLiteral("\"\n");
    }

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        qWarning() << "ThemeLoader: cannot write custom theme:" << path;
        return false;
    }
    file.write(out.toUtf8());
    file.close();
    return true;
}
