#include "services/themeloader.h"
#define TOML_HEADER_ONLY 1
#include "third_party/toml.hpp"
#include <QFile>
#include <QDir>
#include <QDebug>

QMap<QString, QColor> ThemeLoader::s_defaults = {
    // The shared obsidian base (Bifröst). A preset TOML overrides only
    // `accent`; everything else is inherited from here, so each preset is a
    // one-line accent swap. `muted` is nudged lighter (#6C7177 -> #787E85) to
    // reach WCAG AA 3:1 (large text / UI components) on the lighter obsidian
    // surfaces; the old #6C7177 fell below 3:1 on `surface`.
    {"base", QColor("#1E2126")}, {"mantle", QColor("#1A1D21")},
    {"crust", QColor("#15181C")}, {"surface", QColor("#25292E")},
    {"overlay", QColor("#2F343A")}, {"text", QColor("#E6E1D6")},
    {"subtext", QColor("#A3A8AE")}, {"muted", QColor("#787E85")},
    {"accent", QColor("#D4AA6A")}, {"success", QColor("#56B881")},
    {"warning", QColor("#E0B26C")}, {"error", QColor("#E06C75")},
    {"purple", QColor("#BFA4E0")},
    // Gold ramp — fallback values only. Theme.qml derives the live ramp from
    // `accent`; these matter solely for saveThemeFile() serialisation and any
    // direct C++ read.
    {"gold", QColor("#D4AA6A")}, {"goldMid", QColor("#B8915A")},
    {"goldDeep", QColor("#8C6E44")}, {"goldLight", QColor("#ECD4A6")},
    // Obsidian surfaces (page = deepest .. raise2 = highest).
    {"page", QColor("#15181C")}, {"bgA", QColor("#2D3137")},
    {"bgB", QColor("#1E2126")}, {"panel", QColor("#1E2126")},
    {"panel2", QColor("#25292E")}, {"raise", QColor("#25292E")},
    {"raise2", QColor("#2F343A")}, {"line", QColor("#353B42")},
    {"lineSoft", QColor("#2A2E33")}, {"hair", QColor("#1A1D21")},
    // Atmosphere (sheen/shadowInk are base colours, alpha applied at use site;
    // scrim bakes its alpha into #aarrggbb; goldInk is derived in Theme.qml).
    {"sheen", QColor("#FFF0D7")}, {"shadowInk", QColor("#000000")},
    {"scrim", QColor("#C715181C")}, {"goldInk", QColor("#1A1206")},
    {"knob", QColor("#FFF3DF")},
};

ThemeLoader::ThemeLoader(QObject *parent) : QObject(parent), m_colors(s_defaults) {}

void ThemeLoader::loadTheme(const QString &nameOrPath, const QString &themesDir)
{
    m_colors = s_defaults;
    QString filePath;
    if (QFile::exists(nameOrPath)) {
        filePath = nameOrPath;
    } else if (!themesDir.isEmpty()) {
        filePath = QDir(themesDir).filePath(nameOrPath + ".toml");
    }
    if (filePath.isEmpty() || !QFile::exists(filePath)) {
        qWarning() << "Theme not found:" << nameOrPath;
        emit themeChanged();
        return;
    }
    try {
        auto config = toml::parse_file(filePath.toStdString());
        if (auto colors = config["colors"].as_table()) {
            for (const auto &[key, val] : *colors) {
                if (auto v = val.value<std::string>()) {
                    QString colorStr = QString::fromStdString(*v);
                    QColor c(colorStr);
                    if (c.isValid())
                        m_colors[QString::fromStdString(std::string(key))] = c;
                }
            }
        }
    } catch (const toml::parse_error &err) {
        qWarning() << "Theme parse error:" << err.what();
    }
    emit themeChanged();
}

QColor ThemeLoader::color(const QString &name) const
{
    return m_colors.value(name, s_defaults.value(name, QColor("#ff00ff")));
}

void ThemeLoader::setColor(const QString &name, const QColor &c)
{
    if (name.isEmpty() || !c.isValid())
        return;
    if (m_colors.value(name) == c)
        return;
    m_colors[name] = c;
    emit themeChanged();
}

bool ThemeLoader::saveThemeFile(const QString &path) const
{
    if (path.isEmpty())
        return false;

    // Serialise every canonical token (sorted for a stable diff) as a TOML
    // [colors] table. Tokens carrying alpha (e.g. scrim) round-trip through
    // #aarrggbb; opaque tokens stay #rrggbb.
    QString out = QStringLiteral(
        "# Wayfile custom theme — generated by the Colours settings section.\n"
        "# Edit in-app (Settings -> Look & Feel -> Colours) or by hand.\n"
        "[colors]\n");
    const auto keys = s_defaults.keys();
    for (const QString &key : keys) {
        const QColor c = m_colors.value(key, s_defaults.value(key));
        const QString hex = c.alpha() < 255 ? c.name(QColor::HexArgb)
                                            : c.name(QColor::HexRgb);
        out += key + QStringLiteral(" = \"") + hex + QStringLiteral("\"\n");
    }

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        qWarning() << "ThemeLoader: cannot write custom theme:" << path;
        return false;
    }
    file.write(out.toUtf8());
    file.close();
    return true;
}
